#!/bin/bash
# makeasm
# run make cmd in ASMPATH subdirectories
# cmd = release, debug or clean

ASMPATH=~/Development/asm
DIRS="hello uname history cmdline printenv"

for dir in $DIRS
do
    echo -e "\nRunning make $@ in $ASMPATH/$dir directory..."
    cd $ASMPATH/$dir
    make "$@"
done

echo